defaults: &defaults
  jp2_recipes:
    default_color: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
      -jp2_space sRGB
      -double_buffering 10
      -num_threads 4
      -no_weights
      Clevels=6
      Clayers=8
      Cblk=\{64,64\}
      Cuse_sop=yes
      Cuse_eph=yes
      Corder=RPCL
      ORGgen_plt=yes
      ORGtparts=R
      Stiles=\{1024,1024\}
    default_grey: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
      -jp2_space sLUM
      -double_buffering 10
      -num_threads 4
      -no_weights
      Clevels=6
      Clayers=8
      Cblk=\{64,64\}
      Cuse_sop=yes
      Cuse_eph=yes
      Corder=RPCL
      ORGgen_plt=yes
      ORGtparts=R
      Stiles=\{1024,1024\}
  ffmpeg_path: /home/bluewolf/tools/ffmpeg/ffmpeg
  fits_path: /home/bluewolf/tools/fits/fits.sh
  libreoffice_path: /usr/lib/libreoffice/program/soffice
  kdu_compress_path: /home/bluewolf/tools/KDU74/kdu_compress
development:
  <<: *defaults
test: &TEST
  <<: *defaults
production:
  <<: *defaults
